### ISSUE TITLE
Incorrect bicycle travel time to Utrecht Centraal

### ISSUE THREAD

**Issue by bartromgens** [mathijsromans/reisbrein#1]
If I plan to cycle from 'Laan van Nieuw-Guinea' to 'Utrecht Centraal', I get a bicycle advice that takes 16 minutes, while it only takes me 5-8 minutes. 

Reisbrein link: http://www.reisbrein.nl/reisadvies/Laan%20van%20Nieuw-Guinea/Utrecht%20Centraal

Clicking the map icon shows me a map with two cycle routes: http://yournavigation.org/?flat=52.09179&flon=5.08874&tlat=52.0899358491&tlon=5.10992467403&v=bicycle&fast=1&layer=mapnik
Might be related!?

Screenshot of travel advice:
![image](https://user-images.githubusercontent.com/2451596/33421724-5798a11a-d5b3-11e7-921c-d7f998fd408f.png)

**Comment by mathijsromans** [comment]
I think the longer travel time is caused by the fact that the end point is at the east point of the station. 16 minutes is pretty long, but maybe not a crazy amount of time: according to yournavigation it is 2.85 km.

It is a problem that the map gives two cycle routes. I think that the way we paste query arguments into the url of the interactive map and that it more less works is an undocumented feature by yournavigation.org :-)

**Comment by bartromgens** [comment]
Ah, I see! That is an average speed of ~10 km/h. Looks as if YourNavigation walks the last part into the station because it needs 8 out of 16 minutes for the last 500 m.
